name: CI/CD


on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: build PRD
    
    
    - name: Deploy to my EC2 instance
      uses: easingthemes/ssh-deploy@v2.1.5
      
             
      env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "./"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          TARGET: "/home/ubuntu/SampleExpressApp"
    
    
         
