name: CI/CD


on: 
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout the code
        uses: actions/checkout@v1   
        
        
      - name: deploy ec2
        uses: easingthemes/ssh-deploy@v2.1.5
       
           
             
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
          
    
    
         
