name: CI/CD


on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
     
      #- name: Deploy to Server 1
      #  uses: easingthemes/ssh-deploy@main  
        
      - name: create ssh key
        run: |
          apk add openssh-client
          eval $(ssh-agent -s)
          
          aws s3 cp s3://s3-terraformbe/key-sp.pem /tmp/key-sp.pem
          chmod 0400 /tmp/key-sp.pem /root/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no ubuntu@${PUBLIC_IP} "sudo apt-get update"
        shell: bash
           
             
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          
    
    
         
