name: CI/CD


on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout the files
        uses: actions/checkout@v2
     
      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main    
           
             
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
          TARGET: "/home/ubuntu/var"
    
    
         
